/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/modules/about/views/About.vue')['default']
    DatabaseManagement: typeof import('./src/modules/home/components/DatabaseManagement.vue')['default']
    DatabaseSchemaSetup: typeof import('./src/modules/home/components/DatabaseSchemaSetup.vue')['default']
    DataInsertion: typeof import('./src/modules/home/components/DataInsertion.vue')['default']
    F7App: typeof import('framework7-vue')['f7App']
    F7Badge: typeof import('framework7-vue')['f7Badge']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7BlockTitle: typeof import('framework7-vue')['f7BlockTitle']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Icon: typeof import('framework7-vue')['f7Icon']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListItem: typeof import('framework7-vue')['f7ListItem']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    Home: typeof import('./src/modules/home/views/Home.vue')['default']
    HomePanel: typeof import('./src/modules/home/views/Home/HomePanel.vue')['default']
    PerformanceDashboard: typeof import('./src/modules/home/components/PerformanceDashboard.vue')['default']
  }
}
