/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/modules/about/views/About.vue')['default']
    ActivityView: typeof import('./src/modules/home/views/ActivityView.vue')['default']
    AddExpenseSheet: typeof import('./src/modules/expenses/components/AddExpenseSheet.vue')['default']
    CreateGroupSheet: typeof import('./src/modules/groups/components/CreateGroupSheet.vue')['default']
    F7App: typeof import('framework7-vue')['f7App']
    F7Badge: typeof import('framework7-vue')['f7Badge']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7BlockTitle: typeof import('framework7-vue')['f7BlockTitle']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Card: typeof import('framework7-vue')['f7Card']
    F7CardContent: typeof import('framework7-vue')['f7CardContent']
    F7Chip: typeof import('framework7-vue')['f7Chip']
    F7Fab: typeof import('framework7-vue')['f7Fab']
    F7Icon: typeof import('framework7-vue')['f7Icon']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListInput: typeof import('framework7-vue')['f7ListInput']
    F7ListItem: typeof import('framework7-vue')['f7ListItem']
    F7LoginScreenTitle: typeof import('framework7-vue')['f7LoginScreenTitle']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7PageContent: typeof import('framework7-vue')['f7PageContent']
    F7Popup: typeof import('framework7-vue')['f7Popup']
    F7Searchbar: typeof import('framework7-vue')['f7Searchbar']
    F7Segmented: typeof import('framework7-vue')['f7Segmented']
    F7Sheet: typeof import('framework7-vue')['f7Sheet']
    F7Subnavbar: typeof import('framework7-vue')['f7Subnavbar']
    F7SwipeoutActions: typeof import('framework7-vue')['f7SwipeoutActions']
    F7SwipeoutButton: typeof import('framework7-vue')['f7SwipeoutButton']
    F7Tab: typeof import('framework7-vue')['f7Tab']
    F7Tabs: typeof import('framework7-vue')['f7Tabs']
    F7Toggle: typeof import('framework7-vue')['f7Toggle']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    GroupDetail: typeof import('./src/modules/groups/views/GroupDetail.vue')['default']
    GroupsList: typeof import('./src/modules/groups/views/GroupsList.vue')['default']
    Home: typeof import('./src/modules/home/views/Home.vue')['default']
    HomePanel: typeof import('./src/modules/home/views/Home/HomePanel.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
    ProfileView: typeof import('./src/modules/home/views/ProfileView.vue')['default']
  }
}
